deploy_dev:
  stage: deploy
  image: debian:buster
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y && apt-get install rsync -y)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - rsync -avz -e ssh --exclude='.git/' --exclude='.svn/'  --exclude='.gitlab-ci.yml' ./ deployer@35.203.47.37:"/var/www/html || true"
  only:
    - dev

deploy_production:
  stage: deploy
  image: debian:buster
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y && apt-get install rsync -y)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - rsync -avz -e ssh --exclude='.git/' --exclude='.svn/'  --exclude='.gitlab-ci.yml' ./ deployer@35.203.47.37:"/var/www/html || true"
  only:
    - master